src/Entity/Card.php
<?php

namespace App\Entity;

use App\Repository\CardRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CardRepository::class)]
class Card
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $firstname = null;

    #[ORM\Column(length: 255)]
    private ?string $lastname = null;

    #[ORM\Column(length: 255)]
    private ?string $role = null;

    #[ORM\Column(length: 255)]
    private ?string $rank = null;

    #[ORM\Column(nullable: true)]
    private ?int $number = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE)]
    private ?\DateTimeImmutable $birthdate = null;

    #[ORM\Column(length: 255)]
    private ?string $picture = null;

    #[ORM\Column(length: 11)]
    private ?string $uid = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $legal_text = null;

    #[ORM\Column(length: 255)]
    private ?string $role_type = null;

    #[ORM\Column]
    private ?bool $to_print = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\ManyToOne(inversedBy: 'cards')]
    private ?Employee $employee = null;

    #[ORM\ManyToOne(inversedBy: 'cards')]
    private ?PrintRequest $printRequest = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $rank_picture = null;

    public function __construct()
    {
        $this->setCreatedAt(new \DateTimeImmutable());
    }

    public static function createFromEmployee(Employee $employee): Card
    {
        return (new Card())
            ->setFirstname($employee->getFirstname())
            ->setLastname($employee->getLastname())
            ->setBirthdate($employee->getBirthdate())
            ->setNumber($employee->getBadgeNumber())
            ->setRoleType($employee->getRoleType())
            ->setRank($employee->getRankValue())
            ->setRole($employee->getRoleValue())
            ->setRankPicture($employee->getRank()->getPicture())
            ->setPicture($employee->getPicture())
            ->setToPrint(true)
            ->setEmployee($employee);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getRole(): ?string
    {
        return $this->role;
    }

    public function setRole(string $role): self
    {
        $this->role = $role;

        return $this;
    }

    public function getRank(): ?string
    {
        return $this->rank;
    }

    public function setRank(string $rank): self
    {
        $this->rank = $rank;

        return $this;
    }

    public function getNumber(): ?int
    {
        return $this->number;
    }

    public function setNumber(?int $number): self
    {
        $this->number = $number;

        return $this;
    }

    public function getBirthdate(): ?\DateTimeImmutable
    {
        return $this->birthdate;
    }

    public function setBirthdate(\DateTimeImmutable $birthdate): self
    {
        $this->birthdate = $birthdate;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getUid(): ?string
    {
        return $this->uid;
    }

    public function setUid(string $uid): self
    {
        $this->uid = $uid;

        return $this;
    }

    public function getLegalText(): ?string
    {
        return $this->legal_text;
    }

    public function setLegalText(string $legal_text): self
    {
        $this->legal_text = $legal_text;

        return $this;
    }

    public function getRoleType(): ?string
    {
        return $this->role_type;
    }

    public function setRoleType(string $role_type): self
    {
        $this->role_type = $role_type;

        return $this;
    }

    public function isToPrint(): ?bool
    {
        return $this->to_print;
    }

    public function setToPrint(bool $to_print): self
    {
        $this->to_print = $to_print;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getEmployee(): ?Employee
    {
        return $this->employee;
    }

    public function setEmployee(?Employee $employee): self
    {
        $this->employee = $employee;

        return $this;
    }

    public function getPrintRequest(): ?PrintRequest
    {
        return $this->printRequest;
    }

    public function setPrintRequest(?PrintRequest $printRequest): self
    {
        $this->printRequest = $printRequest;

        return $this;
    }

    public function getRankPicture(): ?string
    {
        return $this->rank_picture;
    }

    public function setRankPicture(?string $rank_picture): self
    {
        $this->rank_picture = $rank_picture;

        return $this;
    }
}

src/Form/CardType.php
<?php

namespace App\Form;

use App\Entity\Card;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CardType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('firstname')
            ->add('lastname')
            ->add('role')
            ->add('rank')
            ->add('number', NumberType::class, [
                'label' => 'Badge number',
                'required' => false
            ])
            ->add('uid', null, [
                'help' => "Unique Identifier"
            ])
            ->add('legalText', TextareaType::class, [
                'help' => 'Ce texte apparaît au dos de la carte et définit les droits et attributions que confère la carte à son détenteur en fonction de son rôle au sein de la PRM.',
                'attr' => [
                    'style' => 'min-height: auto;'
                ]
            ])
            ->add('roleType', ChoiceType::class, [
                'choices' => [
                    'Civil' => 'Civil',
                    'Police' => 'Police'
                ]
            ])
            ->add('toPrint', CheckboxType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Card::class,
        ]);
    }
}

src/Controller/CardController.php
<?php

namespace App\Controller;

use App\Entity\Card;
use App\Form\CardType;
use App\Repository\CardRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use function Symfony\Component\Translation\t;

#[Route('/card')]
class CardController extends BaseController
{
    #[Route('', name: 'app.card.index', methods: ['GET'])]
    public function index(CardRepository $cardRepository): Response
    {
        return $this->render('card/index.html.twig', [
            'cards' => $cardRepository->findAll(),
        ]);
    }

    #[Route('/{id}', name: 'app.card.show', methods: ['GET'])]
    public function show(Card $card): Response
    {
        return $this->render('card/show.html.twig', [
            'card' => $card,
        ]);
    }

    #[Route('/{id}/modifier', name: 'app.card.edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Card $card, CardRepository $cardRepository): Response
    {
        $form = $this->createForm(CardType::class, $card);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $card->setUpdatedAt(new \DateTimeImmutable());
            $cardRepository->save($card, true);

            return $this->redirectToRoute('app.card.show', ['id' => $card->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('card/edit.html.twig', [
            'card' => $card,
            'form' => $form,
        ]);
    }


    #[Route('/{id}/imprime', name: 'app.card.printed', methods: ['POST'])]
    public function printed(Request $request, Card $card, CardRepository $cardRepository): Response
    {
        if ($this->isCsrfTokenValid('printed'.$card->getId(), $request->request->get('_token'))) {
            $card->setToPrint(!$card->isToPrint());
            $card->setUpdatedAt(new \DateTimeImmutable());
            $cardRepository->save($card, true);
        }

        return $this->redirectToRoute('app.card.show', ['id' => $card->getId()], Response::HTTP_SEE_OTHER);
    }

    #[Route('/{id}', name: 'app.card.delete', methods: ['POST'])]
    public function delete(Request $request, Card $card, CardRepository $cardRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$card->getId(), $request->request->get('_token'))) {
            $cardRepository->remove($card, true);
        }

        return $this->redirectToRoute('app.card.index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/card/_delete_form.html.twig
<form method="post" action="{{ path('app.card.delete', {'id': card.id}) }}" class="form-button">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ card.id) }}">
    <button class="action-item" data-confirm="Cliquer pour supprimer">
        <span class="icon"><i data-feather="trash-2"></i></span>
        <span class="text" data-confirm-replace>Supprimer</span>
    </button>
</form>

templates/card/_form.html.twig
<div class="card p3">
    {{ form_start(form) }}
    <section class="stack-large">
        <section class="stack">
            <div class="grid">
                {{ form_row(form.rank) }}
                {{ form_row(form.firstname) }}
                {{ form_row(form.lastname) }}
                {{ form_row(form.uid) }}
                {{ form_row(form.number) }}
                {{ form_row(form.role) }}
                {{ form_row(form.roleType) }}
            </div>
            <div class="stack">
                {{ form_row(form.legalText, {attr: {"style": "min-height: 100px"}}) }}
                {{ form_row(form.toPrint) }}
            </div>
        </section>
        <section>
            <button type="submit" class="btn-gradient">{{ button_label|default('Enregistrer') }}</button>
        </section>
    </section>
    {{ form_end(form) }}
</div>

templates/card/_printed_form.html.twig
{% if card.toPrint %}
<form method="post" action="{{ path('app.card.printed', {'id': card.id}) }}" class="form-button">
    <input type="hidden" name="_token" value="{{ csrf_token('printed' ~ card.id) }}">
    <button class="action-item" data-confirm="Marquer comme imprimé">
        <span class="icon"><i data-feather="check"></i></span>
        <span class="text" data-confirm-replace>Marquer imprimé</span>
    </button>
</form>
{% else %}
<form method="post" action="{{ path('app.card.printed', {'id': card.id}) }}" class="form-button">
    <input type="hidden" name="_token" value="{{ csrf_token('printed' ~ card.id) }}">
    <button class="action-item" data-confirm="Définir comme à imprimer">
        <span class="icon"><i data-feather="printer"></i></span>
        <span class="text" data-confirm-replace>Définir à imprimer</span>
    </button>
</form>
{% endif %}

templates/card/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier une carte{% endblock %}

{% block body %}
    <h1 class="h4"><a href="{{ path('app.card.show', {id: card.id}) }}" class="btn-back"> <i data-feather="chevron-left"></i> </a> Modifier la carte de {{ card.employee }}</h1>

    {{ include('card/_form.html.twig', {'button_label': 'Mettre à jour'}) }}
{% endblock %}

templates/card/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cartes{% endblock %}

{% block body %}
    <header>
        <h1 class="h2">Cartes</h1>
    </header>

    <table class="table">
        <thead>
            <tr>
                <th class="key">id</th>
                <th>Titre/grade</th>
                <th>Prénom</th>
                <th>Nom de famille</th>
                <th>
                    <span class="text-muted text-small">Identifiant Unique</span><br>
                    UID
                </th>
                <th>À imprimer</th>
                <th>Date de création</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for card in cards %}
            <tr>
                <th class="key">{{ card.id }}</th>
                <td>{{ card.rank }}</td>
                <td>{{ card.firstname }}</td>
                <td>{{ card.lastname }}</td>
                <td>{{ card.uid }}</td>
                <td>{{ card.toPrint ? 'Yes' : 'No' }}</td>
                <td>{{ card.createdAt ? card.createdAt|date('d/m/Y H:i:s') : '' }}</td>
                <td class="flex flex-end" style="gap: 8px">
                    <a href="{{ path('app.card.show', {'id': card.id}) }}" class="btn btn-sm">Afficher</a>
                    <a href="{{ path('app.card.edit', {'id': card.id}) }}" class="btn btn-sm">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="16">Aucune carte trouvée</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/card/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Card{% endblock %}

{% block body %}
    <h1 class="h2 title-header"><a href="{{ path('app.card.index') }}" class="btn-back"> <i data-feather="chevron-left"></i></a> Carte de {{ card.employee }}</h1>
    <div class="layout-sidebar">
        <table>
            <tbody>
            <tr>
                <th style="min-width: 200px">Employé</th>
                <th><a href="{{ path('app.employee.show', {'id': card.employee.id}) }}">{{ card.employee }} <i data-feather="link-2"></i></a></th>
            </tr>
            <tr>
                <th class="mono key">Photo</th>
                <td class="mono"><img src="{{ vich_uploader_asset(card.employee) }}" style="width: 175px" alt="{{ card.employee }}"></td>
            </tr>
            <tr>
                <th class="mono key">Id</th>
                <td class="mono">{{ card.id }}</td>
            </tr>
            <tr>
                <th class="mono key">
                    UID <br>
                    <div class="text-small text-muted">Identifiant unique</div>
                </th>
                <td class="mono">{{ card.uid }}</td>
            </tr>
            <tr>
                <th class="mono key">Titre/grade</th>
                <td class="mono">
                    <img src="{{ asset('pictures/ranks/'~card.rankPicture) }}" style="height: 100px" alt="Insigne du grade">
                    {{ card.rank }}
                </td>
            </tr>
            <tr>
                <th class="mono key">Prénom</th>
                <td class="mono">{{ card.firstname }}</td>
            </tr>
            <tr>
                <th class="mono key">Nom de famille</th>
                <td class="mono">{{ card.lastname }}</td>
            </tr>
            <tr>
                <th class="mono key">Fonction</th>
                <td class="mono">{{ card.role }}</td>
            </tr>
            <tr>
                <th class="mono key">Type de fonction</th>
                <td class="mono">{{ card.roleType }}</td>
            </tr>
            <tr>
                <th class="mono key">Matricule</th>
                <td class="mono">{{ card.number ?? "Pas de matricule" }}</td>
            </tr>
            <tr>
                <th class="mono key">Texte légal</th>
                <td class="mono">{{ card.legalText }}</td>
            </tr>
            <tr>
                <th class="mono key">À imprimer</th>
                <td class="mono">{{ card.toPrint ? 'Oui' : "Non" }}</td>
            </tr>
            <tr>
                <th class="mono key">Date de création</th>
                <td class="mono">{{ card.createdAt ? card.createdAt|date('d/m/Y H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th class="mono key">Dernière modification</th>
                <td class="mono">{{ card.updatedAt ? card.updatedAt|date('d/m/Y H:i:s') : 'Aucune modification enregistrée' }}</td>
            </tr>
            </tbody>
        </table>
        <div class="stack">
            <div class="action-container block">
                <a href="{{ path('app.card.edit', {'id': card.id}) }}" class="action-item">
                    <span class="icon"><i data-feather="edit-2"></i></span>
                    <span class="text">Modifier</span>
                </a>
                {{ include('card/_printed_form.html.twig') }}
                {{ include('card/_delete_form.html.twig') }}

            </div>
        </div>

    </div>
{% endblock %}