src/Entity/Card.php
<?php

namespace App\Entity;

use App\Repository\CardRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CardRepository::class)]
class Card
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $firstname = null;

    #[ORM\Column(length: 255)]
    private ?string $lastname = null;

    #[ORM\Column(length: 255)]
    private ?string $role = null;

    #[ORM\Column(length: 255)]
    private ?string $rank = null;

    #[ORM\Column(nullable: true)]
    private ?int $number = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE)]
    private ?\DateTimeImmutable $birthdate = null;

    #[ORM\Column(length: 255)]
    private ?string $picture = null;

    #[ORM\Column(length: 11)]
    private ?string $uid = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $legal_text = null;

    #[ORM\Column(length: 255)]
    private ?string $role_type = null;

    #[ORM\Column]
    private ?bool $to_print = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\ManyToOne(inversedBy: 'cards')]
    private ?Employee $employee = null;

    #[ORM\ManyToOne(inversedBy: 'cards')]
    private ?PrintRequest $printRequest = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $rank_picture = null;

    public function __construct()
    {
        $this->setCreatedAt(new \DateTimeImmutable());
    }

    public static function createFromEmployee(Employee $employee): Card
    {
        return (new Card())
            ->setFirstname($employee->getFirstname())
            ->setLastname($employee->getLastname())
            ->setBirthdate($employee->getBirthdate())
            ->setNumber($employee->getBadgeNumber())
            ->setRoleType($employee->getRoleType())
            ->setRank($employee->getRankValue())
            ->setRole($employee->getRoleValue())
            ->setRankPicture($employee->getRank()->getPicture())
            ->setPicture($employee->getPicture())
            ->setToPrint(true)
            ->setEmployee($employee);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getRole(): ?string
    {
        return $this->role;
    }

    public function setRole(string $role): self
    {
        $this->role = $role;

        return $this;
    }

    public function getRank(): ?string
    {
        return $this->rank;
    }

    public function setRank(string $rank): self
    {
        $this->rank = $rank;

        return $this;
    }

    public function getNumber(): ?int
    {
        return $this->number;
    }

    public function setNumber(?int $number): self
    {
        $this->number = $number;

        return $this;
    }

    public function getBirthdate(): ?\DateTimeImmutable
    {
        return $this->birthdate;
    }

    public function setBirthdate(\DateTimeImmutable $birthdate): self
    {
        $this->birthdate = $birthdate;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getUid(): ?string
    {
        return $this->uid;
    }

    public function setUid(string $uid): self
    {
        $this->uid = $uid;

        return $this;
    }

    public function getLegalText(): ?string
    {
        return $this->legal_text;
    }

    public function setLegalText(string $legal_text): self
    {
        $this->legal_text = $legal_text;

        return $this;
    }

    public function getRoleType(): ?string
    {
        return $this->role_type;
    }

    public function setRoleType(string $role_type): self
    {
        $this->role_type = $role_type;

        return $this;
    }

    public function isToPrint(): ?bool
    {
        return $this->to_print;
    }

    public function setToPrint(bool $to_print): self
    {
        $this->to_print = $to_print;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getEmployee(): ?Employee
    {
        return $this->employee;
    }

    public function setEmployee(?Employee $employee): self
    {
        $this->employee = $employee;

        return $this;
    }

    public function getPrintRequest(): ?PrintRequest
    {
        return $this->printRequest;
    }

    public function setPrintRequest(?PrintRequest $printRequest): self
    {
        $this->printRequest = $printRequest;

        return $this;
    }

    public function getRankPicture(): ?string
    {
        return $this->rank_picture;
    }

    public function setRankPicture(?string $rank_picture): self
    {
        $this->rank_picture = $rank_picture;

        return $this;
    }
}

src/Entity/PrintRequest.php
<?php

namespace App\Entity;

use App\Data\PrintData;
use App\Repository\PrintRequestRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PrintRequestRepository::class)]
class PrintRequest
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $printed_at = null;

    #[ORM\OneToMany(mappedBy: 'printRequest', targetEntity: Card::class)]
    private Collection $cards;

    public function __construct()
    {
        $this->cards = new ArrayCollection();
        $this->setCreatedAt(new \DateTimeImmutable());
    }

    public static function fromData(PrintData $data): PrintRequest
    {
        return (new PrintRequest())
            ->addCards($data->getCards())
            ;
    }

    public function getData(): PrintData
    {
        return (new PrintData())
            ->setCards($this->getCards()->toArray());
    }

    public function updateFromData(PrintData $data): self
    {
        foreach ($this->getCards() as $card) {
            $this->removeCard($card);
        }
        $this->addCards($data->getCards());
        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getPrintedAt(): ?\DateTimeImmutable
    {
        return $this->printed_at;
    }

    public function setPrintedAt(?\DateTimeImmutable $printed_at): self
    {
        $this->printed_at = $printed_at;

        return $this;
    }

    /**
     * @return Collection<int, Card>
     */
    public function getCards(): Collection
    {
        return $this->cards;
    }

    public function addCard(Card $card): self
    {
        if (!$this->cards->contains($card)) {
            $this->cards->add($card);
            $card->setPrintRequest($this);
        }

        return $this;
    }

    public function addCards(array|Collection $cards): self
    {
        foreach ($cards as $card) {
            $this->addCard($card);
        }

        return $this;
    }

    public function removeCard(Card $card): self
    {
        if ($this->cards->removeElement($card)) {
            // set the owning side to null (unless already changed)
            if ($card->getPrintRequest() === $this) {
                $card->setPrintRequest(null);
            }
        }

        return $this;
    }

    public function printed(): self
    {
        $this->setPrintedAt(new \DateTimeImmutable());
        return $this;
    }

    public function isPrinted(): bool
    {
        return !is_null($this->getPrintedAt());
    }
}

src/Controller/PrintController.php
<?php

namespace App\Controller;

use App\Data\PrintData;
use App\Entity\PrintRequest;
use App\Form\PrintRequestType;
use App\Repository\PrintRequestRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/impression')]
class PrintController extends BaseController
{
    #[Route('', name: 'app.print.index', methods: ['GET'])]
    public function index(PrintRequestRepository $printRequestRepository): Response
    {
        return $this->render('print/index.html.twig', [
            'print_requests' => $printRequestRepository->findAll(),
        ]);
    }

    #[Route('/nouvelle', name: 'app.print.new', methods: ['GET', 'POST'])]
    public function new(Request $request, PrintRequestRepository $printRequestRepository): Response
    {
        $data = new PrintData();
        $form = $this->createForm(PrintRequestType::class, $data);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $printRequestRepository->save(PrintRequest::fromData($data), true);

            return $this->redirectToRoute('app.print.index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('print/new.html.twig', [
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app.print.show', methods: ['GET'])]
    public function show(PrintRequest $printRequest): Response
    {
        return $this->render('print/show.html.twig', [
            'print_request' => $printRequest,
        ]);
    }

    #[Route('/{id}/modifier', name: 'app.print.edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, PrintRequest $printRequest, PrintRequestRepository $printRequestRepository): Response
    {
        $form = $this->createForm(PrintRequestType::class, $printRequest);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $printRequestRepository->save($printRequest, true);

            return $this->redirectToRoute('app.print.index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('print/edit.html.twig', [
            'print_request' => $printRequest,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app.print.delete', methods: ['POST'])]
    public function delete(Request $request, PrintRequest $printRequest, PrintRequestRepository $printRequestRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$printRequest->getId(), $request->request->get('_token'))) {
            $printRequestRepository->remove($printRequest, true);
        }

        return $this->redirectToRoute('app.print.index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/print/_delete_form.html.twig
<form method="post" action="{{ path('app.print.delete', {'id': print_request.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ print_request.id) }}">
    <button class="btn">Delete</button>
</form>

templates/print/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit PrintRequest{% endblock %}

{% block body %}
    <h1>Edit PrintRequest</h1>

    {{ include('print/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app.print.index') }}">back to list</a>

    {{ include('print/_delete_form.html.twig') }}
{% endblock %}

templates/print/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}PrintRequest index{% endblock %}

{% block body %}
    <h1>PrintRequest index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Created_at</th>
                <th>Printed_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for print_request in print_requests %}
            <tr>
                <td>{{ print_request.id }}</td>
                <td>{{ print_request.createdAt ? print_request.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ print_request.printedAt ? print_request.printedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app.print.show', {'id': print_request.id}) }}">show</a>
                    <a href="{{ path('app.print.edit', {'id': print_request.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app.print.new') }}">Create new</a>
{% endblock %}

templates/print/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New PrintRequest{% endblock %}

{% block body %}
    <h1>Create new PrintRequest</h1>

    {{ include('print/_form.html.twig') }}

    <a href="{{ path('app.print.index') }}">back to list</a>
{% endblock %}

templates/print/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}PrintRequest{% endblock %}

{% block body %}
    <h1>PrintRequest</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ print_request.id }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ print_request.createdAt ? print_request.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Printed_at</th>
                <td>{{ print_request.printedAt ? print_request.printedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app.print.index') }}">back to list</a>

    <a href="{{ path('app.print.edit', {'id': print_request.id}) }}">edit</a>

    {{ include('print/_delete_form.html.twig') }}
{% endblock %}