src/Entity/Employee.php
<?php

namespace App\Entity;

use App\Repository\EmployeeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: EmployeeRepository::class)]
#[Vich\Uploadable()]
class Employee
{
    const GENDER_NAMES = [
        "Non-défini",
        "Femme",
        "Homme"
    ];

    const TYPE_NAMES = [
        true => 'Police',
        false => 'Civil'
    ];

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $firstname = null;

    #[ORM\Column(length: 255)]
    private ?string $lastname = null;

    #[ORM\Column(nullable: true)]
    private ?int $badge_number = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE, nullable: true)]
    private ?\DateTimeImmutable $birthdate = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $phone_number = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $email = null;

    #[ORM\Column]
    private ?bool $isPolice = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $picture = null;

    #[Vich\UploadableField(mapping: "employees", fileNameProperty: "picture")]
    #[Assert\File(mimeTypes: [
        "image/png",
        "image/jpg",
        "image/jpeg",
    ])]
    private ?File $pictureFile = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\ManyToOne(inversedBy: 'employees')]
    private ?Role $role = null;

    #[ORM\ManyToOne(inversedBy: 'employees')]
    private ?Rank $rank = null;

    #[ORM\Column]
    private ?int $gender = null;

    #[ORM\OneToMany(mappedBy: 'employee', targetEntity: Card::class)]
    private Collection $cards;

    public function __construct()
    {
        $this->cards = new ArrayCollection();
        $this->setCreatedAt(new \DateTimeImmutable());
        $this->setIsPolice(false);
        $this->setGender(0);
        $this->setPhoneNumber("+41218111919");
    }

    public function __toString(): string
    {
        return $this->getFullname();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return strtoupper($this->lastname);
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFullname(): string
    {
        return $this->getRankAbbreviation() . " " . $this->getLastname() . " " . $this->getFirstname();
    }

    public function getBadgeNumber(): ?int
    {
        return $this->badge_number;
    }

    public function setBadgeNumber(?int $badge_number): self
    {
        $this->badge_number = $badge_number;

        return $this;
    }

    public function getBirthdate(): ?\DateTimeImmutable
    {
        return $this->birthdate;
    }

    public function setBirthdate(?\DateTimeImmutable $birthdate): self
    {
        $this->birthdate = $birthdate;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(?string $phone_number): self
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function isIsPolice(): ?bool
    {
        return $this->isPolice;
    }

    public function setIsPolice(bool $isPolice): self
    {
        $this->isPolice = $isPolice;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function setPictureFile(File $file = null): self
    {
        $this->pictureFile = $file;

        if ($file) {
            $this->setUpdatedAt(new \DateTimeImmutable('now'));
        }
        return $this;
    }

    public function getPictureFile(): ?File
    {
        return $this->pictureFile;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getRole(): ?Role
    {
        return $this->role;
    }

    public function getRoleValue(): string
    {
        return $this->getRole()->getValue()[$this->getGender()];
    }

    public function setRole(?Role $role): self
    {
        $this->role = $role;

        return $this;
    }

    public function getRank(): ?Rank
    {
        return $this->rank;
    }

    public function getRankValue(): string
    {
        return $this->getRank()->getValue()[$this->getGender()];
    }

    public function getRankAbbreviation(): string
    {
        return $this->getRank()->getAbbreviation()[$this->getGender()];
    }

    public function setRank(?Rank $rank): self
    {
        $this->rank = $rank;

        return $this;
    }

    public function getGender(): ?int
    {
        return $this->gender;
    }

    public function setGender(int $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    /**
     * @return Collection<int, Card>
     */
    public function getCards(): Collection
    {
        return $this->cards;
    }

    public function addCard(Card $card): self
    {
        if (!$this->cards->contains($card)) {
            $this->cards->add($card);
            $card->setEmployee($this);
        }

        return $this;
    }

    public function removeCard(Card $card): self
    {
        if ($this->cards->removeElement($card)) {
            // set the owning side to null (unless already changed)
            if ($card->getEmployee() === $this) {
                $card->setEmployee(null);
            }
        }

        return $this;
    }

    public function getGenderName(): string
    {
        return self::GENDER_NAMES[$this->getGender()];
    }

    public function getRoleType(): string
    {
        return self::TYPE_NAMES[$this->isIsPolice()];
    }

}

src/Form/EmployeeType.php
<?php

namespace App\Form;

use App\Entity\Employee;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichFileType;
use Vich\UploaderBundle\Form\Type\VichImageType;

class EmployeeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('rank', null, [
                'label' => "Rank/Title"
            ])
            ->add('firstname')
            ->add('lastname')
            ->add('birthdate', null, [
                'widget' => "single_text"
            ])
            ->add('gender', ChoiceType::class, [
                'choices' => [
                    'Non défini' => 0,
                    'Femme' => 1,
                    'Homme' => 2
                ]
            ])
            ->add('role')
            ->add('phone_number')
            ->add('email')
            ->add('pictureFile', VichFileType::class, [
                'download_label' => false,
                'required' => false
            ])
            ->add('badge_number')
            ->add('isPolice')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Employee::class,
        ]);
    }
}

src/Controller/EmployeeController.php
<?php

namespace App\Controller;

use App\Data\VCardData;
use App\Entity\Card;
use App\Entity\Employee;
use App\Form\CardType;
use App\Form\EmployeeType;
use App\Form\VirtualCardType;
use App\Repository\CardRepository;
use App\Repository\EmployeeRepository;
use App\Service\CardService;
use App\Service\VirtualCardService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/personnel')]
class EmployeeController extends BaseController
{
    #[Route('', name: 'app.employee.index', methods: ['GET'])]
    public function index(EmployeeRepository $employeeRepository): Response
    {
        return $this->render('employee/index.html.twig', [
            'employees' => $employeeRepository->findAll(),
        ]);
    }

    #[Route('/nouveau', name: 'app.employee.new', methods: ['GET', 'POST'])]
    public function new(Request $request, EmployeeRepository $employeeRepository): Response
    {
        $employee = new Employee();
        $form = $this->createForm(EmployeeType::class, $employee);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $employeeRepository->save($employee, true);

            return $this->redirectToRoute('app.employee.show', ['id' => $employee->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('employee/new.html.twig', [
            'employee' => $employee,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app.employee.show', methods: ['GET'])]
    public function show(Employee $employee): Response
    {
        return $this->render('employee/show.html.twig', [
            'employee' => $employee,
        ]);
    }

    #[Route('/{id}/modifier', name: 'app.employee.edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Employee $employee, EmployeeRepository $employeeRepository): Response
    {
        $form = $this->createForm(EmployeeType::class, $employee);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $employee->setUpdatedAt(new \DateTimeImmutable());
            $employeeRepository->save($employee, true);

            return $this->redirectToRoute('app.employee.index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('employee/edit.html.twig', [
            'employee' => $employee,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/nouvelle-carte', name: 'app.employee.create_card', methods: ['GET', 'POST'])]
    public function createCard(Request $request, Employee $employee, CardService $cardService, EntityManagerInterface $em, CardRepository $cardRepository): Response
    {
        if(!$this->isGranted('CARD_CREATE', $employee)) {
            $this->addNotification("Veuillez vous assurer que tous les pré-requis de la création d'une carte sont remplis pour cet employé. <a href=\"#\">Voir la documentation</a>");
            return $this->redirectToRoute('app.employee.show', ['id' => $employee->getId()], Response::HTTP_SEE_OTHER);
        }

        $card = $cardService->create($employee);

        $form = $this->createForm(CardType::class, $card);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $cardRepository->save($card, true);
            return $this->redirectToRoute('app.employee.show', ['id' => $employee->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->render('employee/create_card.html.twig', [
            'employee' => $employee,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}/carte-virtuelle', name: 'app.employee.create_vcard', methods: ['GET', 'POST'])]
    public function getVCard(Request $request, Employee $employee, VirtualCardService $virtualCardService): Response
    {
        $data = VCardData::createFromEmployee($employee);
        $form = $this->createForm(VirtualCardType::class, $data);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $vcard = $virtualCardService->create($data);

            $path = 'cards/'.time().'.vcf';
            file_put_contents('cards/'.time().'.vcf', $vcard->serialize());
            $file = new File($path);

            return $this->file($file);
        }

        return $this->renderForm('employee/create_vcard.html.twig', [
            'employee' => $employee,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app.employee.delete', methods: ['POST'])]
    public function delete(Request $request, Employee $employee, EmployeeRepository $employeeRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$employee->getId(), $request->request->get('_token'))) {
            $employeeRepository->remove($employee, true);
        }

        return $this->redirectToRoute('app.employee.index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/employee/_delete_form.html.twig
<form method="post" action="{{ path('app.employee.delete', {'id': employee.id}) }}" class="form-button">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ employee.id) }}">
    <button class="action-item" data-confirm="Cliquer pour supprimer">
        <span class="icon"><i data-feather="trash-2"></i></span>
        <span class="text" data-confirm-replace>Supprimer</span>
    </button>
</form>

templates/employee/_form.html.twig
<div class="card p3">
    {{ form_start(form) }}
    <section class="stack-large">
        <section class="stack">
            <div class="grid">
                {{ form_row(form.rank) }}
                {{ form_row(form.firstname) }}
                {{ form_row(form.lastname) }}
                {{ form_row(form.birthdate) }}
                {{ form_row(form.gender) }}
                {{ form_row(form.role) }}
                {{ form_row(form.phone_number) }}
                {{ form_row(form.email) }}
                {{ form_row(form.badge_number) }}
                {{ form_row(form.isPolice) }}
            </div>
            <div class="stack">
                {{ form_row(form.pictureFile) }}
            </div>
        </section>
        <section>
            <button type="submit" class="btn-gradient">{{ button_label|default('Enregistrer') }}</button>
        </section>
    </section>
    {{ form_end(form) }}
</div>

templates/employee/create_card.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1 class="h2 title-header"><a href="{{ path('app.employee.index') }}" class="btn-back"> <i data-feather="chevron-left"></i></a> Nouvelle carte de {{ employee }}</h1>
    {{ include('components/_card_form.html.twig') }}
{% endblock %}

{% block title %}Nouvell carte de {{ employee }}{% endblock %}

templates/employee/create_vcard.html.twig
{% extends 'base.html.twig' %}

{% block title %}Créer une VCard{% endblock %}

{% block body %}
    <h1 class="h2 md title-header"><a href="{{ path('app.employee.show', {id: employee.id}) }}" class="btn-back"> <i data-feather="chevron-left"></i></a> Nouvelle carte virtuelle de {{ employee }}</h1>
    <div class="card-md p3">
        {{ form_start(form) }}
        <section class="stack-large">
            <section class="stack">
                <div class="grid">
                    {{ form_row(form.nameDisplayType) }}
                    {{ form_row(form.phoneNumber) }}
                </div>
                <div class="stack">
                    {{ form_row(form.email) }}
                </div>
                <div class="hstack">
                    {{ form_row(form.displayRank) }}
                    {{ form_row(form.displayRole) }}
                </div>
            </section>
            <section>
                <button type="submit" class="btn-gradient">Télécharger</button>
            </section>
        </section>
        {{ form_end(form) }}
    </div>

{% endblock %}

templates/employee/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier {{ employee }}{% endblock %}

{% block body %}
    <h1 class="h4"><a href="{{ path('app.employee.show', {id: employee.id}) }}" class="btn-back"> <i data-feather="chevron-left"></i> </a> Modifier {{ employee }}</h1>

    {{ include('employee/_form.html.twig', {'button_label': 'Mettre à jour'}) }}
{% endblock %}

templates/employee/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Personnel{% endblock %}

{% block body %}
    <header>
        <h1 class="h2">Personnel</h1>
        <a href="{{ path('app.employee.new') }}" class="btn-primary btn-small">Nouvel employé</a>
    </header>

    <table class="table">
        <thead>
            <tr>
                <th class="key" style="width: 50px">id</th>
                <th>Nom complet</th>
                <th>Police</th>
                <th>Dernière modification</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for employee in employees %}
            <tr>
                <th class="key">{{ employee.id }}</th>
                <td>{% if employee.cards.count > 0 %}<a href="{{ path('app.card.show', {id: employee.cards.last.id}) }}"><i data-feather="credit-card"></i></a>{% endif %}{{ employee }}</td>
                <td>{{ employee.isPolice ? 'Oui' : 'Non' }}</td>
                <td>{{ employee.updatedAt ? employee.updatedAt|date('d/m/Y H:i:s') : employee.createdAt|date('d/m/Y H:i:s') }}</td>
                <td class="flex flex-end" style="gap: 8px">
                    <a href="{{ path('app.employee.show', {'id': employee.id}) }}" class="btn btn-sm">Afficher</a>
                    <a href="{{ path('app.employee.edit', {'id': employee.id}) }}" class="btn btn-sm">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/employee/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvel employé{% endblock %}

{% block body %}
    <h1 class="h4"><a href="{{ path('app.employee.index') }}" class="btn-back"> <i data-feather="chevron-left"></i> </a> Nouvel employé</h1>
    {{ include('employee/_form.html.twig') }}
{% endblock %}

templates/employee/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ employee }}{% endblock %}

{% block body %}
    <h1 class="h2 title-header"><a href="{{ path('app.employee.index') }}" class="btn-back"> <i data-feather="chevron-left"></i></a> {{ employee }}</h1>
    <div class="layout-sidebar">
        <table>
            <tbody>
            <tr>
                <th class="mono key">Photo</th>
                <td class="mono"><img src="{{ vich_uploader_asset(employee) }}" style="width: 175px" alt="{{ employee }}"></td>
            </tr>
            <tr>
                <th class="mono key">Id</th>
                <td class="mono">{{ employee.id }}</td>
            </tr>
            <tr>
                <th class="mono key">Titre/grade</th>
                <td class="mono">{{ employee.rankValue }}</td>
            </tr>
            <tr>
                <th class="mono key">Prénom</th>
                <td class="mono">{{ employee.firstname }}</td>
            </tr>
            <tr>
                <th class="mono key">Nom de famille</th>
                <td class="mono">{{ employee.lastname }}</td>
            </tr>
            <tr>
                <th class="mono key">Fonction</th>
                <td class="mono">{{ employee.roleValue }}</td>
            </tr>
            <tr>
                <th class="mono key">Police</th>
                <td class="mono">{{ employee.isPolice ? 'Oui' : 'Non' }}</td>
            </tr>
            <tr>
                <th class="mono key">Matricule</th>
                <td class="mono">{{ employee.badgeNumber ?? "Pas de matricule" }}</td>
            </tr>
            <tr>
                <th class="mono key">Date de naissance </th>
                <td class="mono">{{ employee.birthdate ? employee.birthdate|date('d/m/Y') : '' }}</td>
            </tr>
            <tr>
                <th class="mono key">Numéro de télépone</th>
                <td class="mono">{{ employee.phoneNumber }}</td>
            </tr>
            <tr>
                <th class="mono key">Adresse email</th>
                <td class="mono">{{ employee.email }}</td>
            </tr>
            <tr>
                <th class="mono key">Date de création</th>
                <td class="mono">{{ employee.createdAt ? employee.createdAt|date('d/m/Y H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th class="mono key">Dernière modification</th>
                <td class="mono">{{ employee.updatedAt ? employee.updatedAt|date('d/m/Y H:i:s') : 'Aucune modification enregistrée' }}</td>
            </tr>
            <tr>
                <th class="mono key">Genre</th>
                <td class="mono">{{ employee.genderName }}</td>
            </tr>
            </tbody>
        </table>
        <div class="stack">
            <div class="action-container">
                <h4>Cartes</h4>
                {% for card in employee.cards %}
                    <a href="{{ path('app.card.show', {'id': card.id}) }}" class="action-item">
                        <span class="icon"><i data-feather="chevron-right"></i></span>
                        <span class="content">
                            <span class="text">Carte de police</span>
                            <span class="details">{{ card.uid }}</span>
                        </span>
                    </a>
                {% else %}
                    <div class="empty-list">
                        <i data-feather="help-circle"></i>
                        <p>Aucune carte crée</p>
                    </div>
                {% endfor %}
            </div>
            <div class="action-container block">
                <a href="{{ path('app.employee.create_card', {'id': employee.id}) }}" class="action-item">
                    <span class="icon"><i data-feather="credit-card"></i></span>
                    <span class="text">Nouvelle carte</span>
                </a>
                <a href="{{ path('app.employee.create_vcard', {'id': employee.id}) }}" class="action-item">
                    <span class="icon"><i data-feather="download"></i></span>
                    <span class="content">
                        <span class="text">Télécharger la vCard</span>
                        <span class="details">(.vcf)</span>
                    </span>
                </a>
                <a href="{{ path('app.employee.edit', {'id': employee.id}) }}" class="action-item">
                    <span class="icon"><i data-feather="edit-2"></i></span>
                    <span class="text">Modifier</span>
                </a>
                {{ include('employee/_delete_form.html.twig') }}

            </div>
        </div>

    </div>
{% endblock %}