src/Entity/Card.php
<?php

namespace App\Entity;

use App\Repository\CardRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CardRepository::class)]
class Card
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $firstname = null;

    #[ORM\Column(length: 255)]
    private ?string $lastname = null;

    #[ORM\Column(length: 255)]
    private ?string $role = null;

    #[ORM\Column(length: 255)]
    private ?string $rank = null;

    #[ORM\Column(nullable: true)]
    private ?int $number = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE)]
    private ?\DateTimeImmutable $birthdate = null;

    #[ORM\Column(length: 255)]
    private ?string $picture = null;

    #[ORM\Column(length: 11)]
    private ?string $uid = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $legal_text = null;

    #[ORM\Column(length: 255)]
    private ?string $role_type = null;

    #[ORM\Column]
    private ?bool $to_print = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\ManyToOne(inversedBy: 'cards')]
    private ?Employee $employee = null;

    #[ORM\ManyToOne(inversedBy: 'cards')]
    private ?PrintRequest $printRequest = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $rank_picture = null;

    public function __construct()
    {
        $this->setCreatedAt(new \DateTimeImmutable());
    }

    public static function createFromEmployee(Employee $employee): Card
    {
        return (new Card())
            ->setFirstname($employee->getFirstname())
            ->setLastname($employee->getLastname())
            ->setBirthdate($employee->getBirthdate())
            ->setNumber($employee->getBadgeNumber())
            ->setRoleType($employee->getRoleType())
            ->setRank($employee->getRankValue())
            ->setRole($employee->getRoleValue())
            ->setRankPicture($employee->getRank()->getPicture())
            ->setPicture($employee->getPicture())
            ->setToPrint(true)
            ->setEmployee($employee);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getRole(): ?string
    {
        return $this->role;
    }

    public function setRole(string $role): self
    {
        $this->role = $role;

        return $this;
    }

    public function getRank(): ?string
    {
        return $this->rank;
    }

    public function setRank(string $rank): self
    {
        $this->rank = $rank;

        return $this;
    }

    public function getNumber(): ?int
    {
        return $this->number;
    }

    public function setNumber(?int $number): self
    {
        $this->number = $number;

        return $this;
    }

    public function getBirthdate(): ?\DateTimeImmutable
    {
        return $this->birthdate;
    }

    public function setBirthdate(\DateTimeImmutable $birthdate): self
    {
        $this->birthdate = $birthdate;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getUid(): ?string
    {
        return $this->uid;
    }

    public function setUid(string $uid): self
    {
        $this->uid = $uid;

        return $this;
    }

    public function getLegalText(): ?string
    {
        return $this->legal_text;
    }

    public function setLegalText(string $legal_text): self
    {
        $this->legal_text = $legal_text;

        return $this;
    }

    public function getRoleType(): ?string
    {
        return $this->role_type;
    }

    public function setRoleType(string $role_type): self
    {
        $this->role_type = $role_type;

        return $this;
    }

    public function isToPrint(): ?bool
    {
        return $this->to_print;
    }

    public function setToPrint(bool $to_print): self
    {
        $this->to_print = $to_print;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getEmployee(): ?Employee
    {
        return $this->employee;
    }

    public function setEmployee(?Employee $employee): self
    {
        $this->employee = $employee;

        return $this;
    }

    public function getPrintRequest(): ?PrintRequest
    {
        return $this->printRequest;
    }

    public function setPrintRequest(?PrintRequest $printRequest): self
    {
        $this->printRequest = $printRequest;

        return $this;
    }

    public function getRankPicture(): ?string
    {
        return $this->rank_picture;
    }

    public function setRankPicture(?string $rank_picture): self
    {
        $this->rank_picture = $rank_picture;

        return $this;
    }
}

templates/components/_card.html.twig
<div class="p-card">
    <div class="p-card__photo" style="background-image: url('{{ vich_uploader_asset(employee) }}')"></div>
    <div class="p-card__details">
        <a href="#" class="c-details__roleType" data-tooltip="<small>Colonne de la base de donnée</small><br><code>roleType</code>">
            {#<div class="__tooltip">
                <div class="text-small">Base de donnée</div>
                <code class="">role_type</code>
            </div>#}
            {{ card.roleType }}
        </a>
        <a href="#" class="c-detail">
            {{ card.rank }}
        </a>
        <a href="#" class="c-details__lastname">
            {{ employee.lastname }}
        </a>
        <a href="#" class="c-details__firstname">
            {{ card.firstname }}
        </a>
        <a href="#" class="c-detail">
            {{ card.role }}
        </a>
    </div>
</div>

templates/components/_card_form.html.twig
{{ form_start(form) }}
<div class="hstack mb2">
<div class="p-card">
    <div class="p-card__photo" style="background-image: url('{{ vich_uploader_asset(employee) }}')"></div>
    <div class="stack" style="--gap: 1">
        {{ form_row(form.rank) }}
        {{ form_row(form.lastname) }}
        {{ form_row(form.firstname) }}
        {{ form_row(form.role) }}
    </div>
    <div class="stack" style="width: 100px; --gap: 1">
        {{ form_row(form.number) }}
        {{ form_row(form.roleType) }}
    </div>
</div>
<div class="p-card">
    <div class="grid">
        {{ form_row(form.uid) }}
        {{ form_row(form.legalText) }}
        {{ form_row(form.toPrint) }}
    </div>
</div>
</div>
<button class="btn-primary">Confirmer</button>
{{ form_end(form) }}

templates/components/_header.html.twig
<header>
    <div class="container flex">
        <div>
            {% if error is defined and error is not same as(null) %}
                {% if error is not same as(null) %}
            <div class="header__error">
                <h1 class="h1">HTTP/2 {{ error.code }}</h1>
                <h2 class="h2">{{ error.desc }} <span class="blink">▉</span></h2>
            </div>
                    {% endif %}
            {% else %}
            <a href="/" class="header__logo">
                <i data-feather="file"></i>
                <span>myDocuments</span>
            </a>
            {% endif %}
        </div>
    </div>
</header>